on:
  push:
    branches:
      - main

env:
  CHECKSTYLE_VERSION: 10.25.1

jobs:
  checkstyle:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: downlaod checkstyle
        run: |
          curl -sL https://github.com/checkstyle/checkstyle/releases/download/checkstyle-${{ env.CHECKSTYLE_VERSION }}/checkstyle-${{ env.CHECKSTYLE_VERSION }}-all.jar -o checkstyle.jar
      - name: run checkstyle
        run: |
          java -jar checkstyle.jar \
            -c checkstyle.xml \
            -f sarif \
            -o checkstyle-report.sarif \
            src/main/java
          EXIT_CODE=$?
          if [ $EXIT_CODE -eq 1 ]; then
            echo "Checkstyle configuration error detected (exit code 1). Failing build."
            exit 1
          elif [ $EXIT_CODE -eq 2 ]; then
            echo "Checkstyle violations found (exit code 2). Continuing without failing."
            exit 0
          else
            echo "Checkstyle ran successfully with exit code $EXIT_CODE."
            exit $EXIT_CODE
          fi
      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'checkstyle-report.sarif'
          category: checkstyle
